project:
  type: website
  output-dir: docs
  
website:
  title: "My Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents: auto
format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true



