
##  Emergency Plans 

###  3 day (Evacuation) 
#### Grab and go:

1. Water
1. Non-perishable food (and dog food)
1. Toiletries
1. Bug-out bags
1. Booze (for bartering)
1. Extra gas
1. Backpacking camping gear
1. 2-way radios
1. Camouflage tarps
1. Take-down bow
1. Bleach

#### Lives in the Car:

1. Tow rope w/ hooks
1. Change of clothes for everyone
1. TP
1. Road maps
1. Basic Car toolkit:
    1. Channel locks
    1. Vice grips
    1. Pliers
    1. Tire gauge
    1. Epoxy putty
    1. Bailing wire
    1. Hose clamps
    1. Voltmeter
    1. Screwdrivers
    1. Portable battery/jumper/air compressor
    1. Inverter
    1. Starting fluid
    1. Socket set
1. Communications:
    1. [PLB](./IoTProjects.html#the-best-damn-radio-system)
    1. Flares
    1. Cell phone chargers
    1. Sharpie and white plastic bags
1. Blanket and towels
1. Fire extinguisher
1. \$300 in Cash and Coin

###  3 week (Power failure) 
1. Genset run from tractor
    1. Refrigeration
    1. Water pump
    1. Electronics
    1. Lights
    1. Radio & TV
1. Woodstove for heat - always keep 5 face cord on hand
1. Solar hot water heater
1. Canned food
1. Propane heater
1. Chainsaw
1. Crank Radio
1. Plastic sheeting

###  3 year (Plan A) 
1. Tools
1. Weapons
    1. Bow
    1. Crossbow
    1. [Sniper rifle](./ShootingProjects.html#f-class-1000yarder)
    1. Sawed-off and hunting shotguns
    1. [SHTF Guns](https://www.youtube.com/watch?v=pW0zw1SOJ8k)
    1. Reload kits
1. Textiles
    1. Rope machine
    1. Foot powered sewing machine
    1. Portable Spinning wheel
    1. Backstrap Loom
1. Mechanical
    1. Forge tools, blower
    1. Files, grinding wheel
    1. Soil drill
1. Navigation
    1. Sextant
    1. Star charts
    1. Mechanical watches
    1. Map library
        1. Nautical
            1. free NOAA charts
        1. Terrestrial
            1. Delorme atlas books
1. [Night vision](https://www.amazon.com/AGM-Asp-Micro-Thermal-Imaging-Monocular/dp/B08CRZZXDL?th=1)
1. Fishing gear
1. Water Treatment
    1. Iodine
    1. Activated carbon
    1. Distiller
1. Medical
  1. Antibiotics
  1. Anesthetics
  1. Suture materials
1. Options
    1. Migrate to more secluded location and take up simple farming
    1. Head North, away from population centers and become migratory coastal hunters/gatherers
1. Food
    1. Seed stash
    1. Can stash
    1. Booze stash
